version: "3"
services:
  app:
    build:
      context: .
      dockerfile: compose_dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ~/desktop/docker/import_nrrd:/segmentation_gui_backend/import_nrrd
      - ~/desktop/docker/export_data:/segmentation_gui_backend/export_data
